[package]
name = "material-converter"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
image = "0.24.7"
ron = "0.8.1"
serde = { version = "1.0.192", features = ["derive"] }
