[package]
name = "material-converter"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.8"
ron = "0.6.0"
serde = "1.0.114"
structopt = "0.3.15"
